### ISSUE TITLE
Add screenshot support

### ISSUE THREAD

**Issue by jaredsburrows** [doorbell/android-sdk#10]
Allow users to screenshot the current view to send bug report feedback

**Comment by Queskr** [comment]
Is this feature planned?

**Comment by manavo** [comment]
There is no ETA for this at the moment unfortunately!

**Comment by Queskr** [comment]
How come? It doesn't have any meaningful roadmap for Android? This is a core feature your competitors have.

We are starting to invest in Doorbell.io as our feedback system. If you do not have plans to invest in it, maybe we should reconsider our selection.

**Comment by manavo** [comment]
It is just around prioritising and managing all the different platforms. The most used platform is the web one, so the mobile platforms are falling a little bit behind in development and the roadmap.

I'll see if I can move this up the priority list, as it does seem fairly straight-forward to add, and it would be good to do more work on these SDKs, can't leave the behind!

I'll update you here with the progress on this, shouldn't be long to get a new release out!

**Comment by Queskr** [comment]
Thank you.

**Comment by manavo** [comment]
Hey @Queskr, there's a new version out now which does enable screenshots, just updating the documentation now for it.

Will try and add a "shake to open" interaction, in order to capture the current view a bit better.

But it is at least a start on the screenshots 🙂

**Comment by Queskr** [comment]
Thanks. Please share a link to the updated documentation once it's updated!

**Comment by manavo** [comment]
Here's the update documentation: https://doorbell.io/docs/android

It includes a little section for screenshots, and shows how to call it in the example.

Thank you for your patience with this!
