### ISSUE TITLE
AppCompat

### ISSUE THREAD

**Issue by jaredsburrows** [doorbell/android-sdk#18]
@manavo Have you considered using `AppCompat` for AlertDialog?

See here: https://developer.android.com/reference/android/support/v7/app/AlertDialog.html

**Comment by manavo** [comment]
Wasn't aware of `AppCompat` for AlertDialog. What would be the benefit of using it?

**Comment by jaredsburrows** [comment]
I was just curious of what you think about making sure its all "material".

**Comment by manavo** [comment]
I didn't think the AlertDialog had changed much with material design. I'll look into the `AppCompat` version though and see if it is worth changing! Thanks for the tip!

**Comment by jaredsburrows** [comment]
Closing this because I think it is best not to depend on a View library.
