### ISSUE TITLE
Newest version

### ISSUE THREAD

**Issue by szaboa** [doorbell/android-sdk#21]
Hi, I would like to know which is the newest stable release?

Because in the README.md version v0.2.9 is mentioned, but there is also a v0.3.0 under Releases.

**Comment by manavo** [comment]
Ah, really sorry about that. The Readme wasn’t updated in the last release, I’ll do that ASAP!

**Comment by manavo** [comment]
I've updated it in the Readme, and made a not to make sure it is kept up to date with future releases.

Sorry again about this, and thanks for highlighting it!

Thanks,
Phil
