### ISSUE TITLE
Support MaterialComponents styling

### ISSUE THREAD

**Issue by jaredsburrows** [doorbell/android-sdk#22]
I do not believe the Material buttons should be touching here. This is using `Theme.MaterialComponents.Light.NoActionBar`.

![screen1575845212](https://user-images.githubusercontent.com/1739848/70397858-a9bc4e80-19ca-11ea-9faf-f6338b3639a0.png)

**Comment by manavo** [comment]
Hey @jaredsburrows! Really appreciate the report for this bug!

I'll setup a demo project using `MaterialComponents` and see how to best solve this.

The `Theme.MaterialComponents.Light.NoActionBar` was the theme of the activity? Or the whole application? (just so I can try and re-create this)

Thanks!

**Comment by jaredsburrows** [comment]
Currently the whole application, I just upgraded from `Theme.AppCompat.Light.NoActionBar`.

**Comment by manavo** [comment]
Hmm, I've just started looking around for this, and definitely not the first to encounter it (https://stackoverflow.com/questions/52829954/materialcomponents-theme-alert-dialog-buttons, https://github.com/material-components/material-components-android/issues/162).

Ideally it seems like Doorbell would extend the `MaterialAlertDialogBuilder` instead in that case, although I'm not sure that's something I could do at runtime.

To solve this I might have to create another class (`MaterialDoorbell`, or something like that), which duplicates everything in the current `Doorbell` class. Although it doesn't feel like a great option...

**Comment by manavo** [comment]
Or need to migrate to support [AndroidX](https://developer.android.com/jetpack/androidx/migrate), and then use `androidx.appcompat.app.AlertDialog` instead of `android.app.AlertDialog`.

I'll keep exploring and work out what works best!

**Comment by jaredsburrows** [comment]
Thanks!

**Comment by manavo** [comment]
Hey @jaredsburrows!

Just to give you a quick update on this, I think it won't be as simple as just migrating to AndroidX, the best option will probably to change it so the `Doorbell` class doesn't extend the `android.app.AlertDialog.Builder` directly.

Instead it can have a `android.app.AlertDialog.Builder` property with a default, and can be changed. So in this case, you could instantiate your own `MaterialAlertDialogBuilder` to pass in instead.

I'll let you know as soon as this is ready!

**Comment by manavo** [comment]
Hey @jaredsburrows! All set now, you can start Doorbell like this:

```java
    // If using Material Components, you can initialize Doorbell like this:
    Doorbell doorbellDialog = new Doorbell(this, appId, apiKey, new MaterialAlertDialogBuilder(this));
```

So you pass in the Dialog you want Doorbell to use, instead of the Doorbell class extending the AlertDialog.Builder directly.

Let me know if you run into any issues!

Thanks,
Phil

**Comment by manavo** [comment]
@jaredsburrows forgot to say, version `0.4.0` has been tagged which has this, so you'll need to upgrade to the latest version!

**Comment by jaredsburrows** [comment]
Thank you!
