### ISSUE TITLE
No way to disable/override toasts when error occurs

### ISSUE THREAD

**Issue by MarkBorazio** [doorbell/android-sdk#24]
It seems that when there is an error, a toast appears.

For example, if I have no internet access and show the Doorbell dialog or try to send a message, the following toast appears: `Unable to resolve host "doorbell.io": No address associated with hostname`
The same thing happened in a recently fixed issue where a toast would appear saying: `No Peer Certificate`.

It would be nice to be able to disable or override these error messages as they are confusing to the user.

**Comment by manavo** [comment]
This should be better documented, but you can use:

```java
        doorbell.setErrorCallback(new RestErrorCallback() {
            @Override
            public void error(String errorMessage) {
                // Handle message
            }
        });
```

Ideally there would also be a version of this which passes the Exceptions, so you can better handle different errors (like connectivity errors vs validation errors).

But that's what's available right now!

**Comment by manavo** [comment]
Sorry @MarkBorazio, was completely wrong on this! This option isn't actually there, so working on adding it now!

Thanks,
Phil

**Comment by manavo** [comment]
I've implemented this now, it will be in the next release. Just need to test some additional things with the other things in the next release and will then tag it!

**Comment by manavo** [comment]
Version `0.4.6` was just tagged and will be available any minute now (when Maven updates). Thanks again for flagging the issue with this @MarkBorazio!

**Comment by manavo** [comment]
`0.4.7` actually, mis-tagged `0.4.6`

**Comment by MarkBorazio** [comment]
Thanks again for the quick turnaround @manavo.
I just had a look and everything seems to be working well.
