### ISSUE TITLE
change toast message when success

### ISSUE THREAD

**Issue by yfsx** [doorbell/android-sdk#3]
hi, i just wanna ask how to change default toast message?
in my condition is when user send error report / feedback to my account, default toast show message "feedback sent!" and i want to change it

thanks!

**Comment by manavo** [comment]
Hey!

If you go to the setup page of your application, and open the "Website/Javascript" section (under SDKs), you'll see the "Look & feel" section. At the bottom there, you can edit the success message.

I know it is in the wrong section of the setup page, but the messages are common for all the SDKs. I'll move it soon!

I'll also try and add an onSuccess callback in the SDK, which will be easier to catch and localise!

**Comment by yfsx** [comment]
that really nice!  i'm agree with your idea to make a callback, it really helps any programmer and make the world so easy >.<

thanks bro

**Comment by manavo** [comment]
Hey!

I've made the change, just waiting for Maven to update with the release. Should be available soon, and I'll update the docs with it!

Thanks again for the suggestion!

**Comment by manavo** [comment]
Hey @yfsx! Just to let you know Maven has updated, and I've updated the docs to show the usage of the new callback: https://doorbell.io/docs/android

Let me know if you run into any problems! And thanks again for the suggestion!
